<?php

return [    
	#'DbPath' => 'http://83.212.86.158:5984/_fti/local/',
        'DbPath' => 'http://83.212.86.158:5984/',
        'lucenePath' =>'_fti/local/',
	'couchUser' => 'dimneg',
	'couchPass' => 'fujintua0)',	
	'winLibraryServername_1' => '127.0.0.1:33067',
	'winLibraryUsername_1' => 'root',
	'winLibraryPassword_1' => "",
	'winLibraryDbname_1' => "library",
	'gemhDb_host' => '83.212.86.156',	
	'gemhDb_user' => 'gemh',
	'gemhDb_pass' => 'gemh@69',
	'gemhDb_name' => 'gemhV2',
	'solrPath' => 'http://83.212.86.164:8983/solr/',	
	'personsSolrCore' => 'LbPersons_v2',
	'FRSolrCore' => 'LbFr_v2',
	'FRcouchDB' => 'lb_fr',
	'MPcouchDB' => 'lb_mp',
	'MPcouchDB_2' => 'lb_mp_2',
	'companiesSolrCore' => 'LbCompanies_v2',
	'companiescouchDB' => 'lb_companies',
	'nonGemhcouchDB' => 'lb_no_gemh',
	'personscouchDB' => 'lb_persons',
        'orgtypescouchDB' =>'lb_orgtypes',
        'chamberscouchDB' =>'lb_chambers',
        'tedcouchDB' =>'yds_corporation_companies_v2',
	'australiaSellersCouchDB'=>'elod_australia_sellers',
	'australiaBuyersCouchDB'=>'elod_australia_buyers',
        'diaugeiaSellersCouchDB'=>'elod_diaugeia_sellers',
	'diaugeiaBuyersCouchDB'=>'elod_diaugeia_buyers',
        'khmdhsSellersCouchDB'=>'elod_sellers',
	'khmdhsBuyersCouchDB'=>'elod_buyers',
        'corporationsCouchDB'=>'yds_corporations',
        'espaCouchDB'=>'elod_espa_beneficiaries',
        'cpa_l1_CouchDB'=>'lb_cpa_l1',
        'markets_CouchDB'=>'lb_markets',
        'postalCodeCouchDB'=>'lb_postal_codes',
        'messagesSearch_CouchDB'=>'lb_search_messages',
	'sparqlServer' => 'http://143.233.226.49:8890',
	'personsUrl' => 'http://dashboard.linkedbusiness.gr/gr/person/', //deprecated
	'companiesUrl' => 'http://dashboard.linkedbusiness.gr/gr/company/', //deprecated
        'personsLbUrl' => '/person/',
	'companiesLbUrl' => '/company/',
        'corporationsUrl' => '/corporate/'
];