<?php

return [    
	#'DbPath' => 'http://83.212.86.158:5984/_fti/local/',
        'DbPath' => 'http://83.212.86.158:5984/',
        'lucenePath' =>'_fti/local/',
	'couchUser' => 'dimneg',
	'couchPass' => 'fujintua0)',	
	'winLibraryServername_1' => '127.0.0.1:33067',
	'winLibraryUsername_1' => 'root',
	'winLibraryPassword_1' => "",
	'winLibraryDbname_1' => "library",
	'gemhDb_host' => '83.212.86.156',	
	'gemhDb_user' => 'gemh',
	'gemhDb_pass' => 'gemh@69',
	'gemhDb_name' => 'gemhV2',
	'solrPath' => 'http://83.212.86.164:8983/solr/',	
	'personsSolrCore' => 'LbPersons_v2',
	'FRSolrCore' => 'LbFr_v2',
	'FRcouchDB' => 'lb_fr',
	'MPcouchDB' => 'lb_mp',
	'MPcouchDB_2' => 'lb_mp_2',
	'companiesSolrCore' => 'LbCompanies_v2',
	'companiescouchDB' => 'lb_companies',
	'nonGemhcouchDB' => 'lb_no_gemh',
	'personscouchDB' => 'lb_persons',
	'sparqlServer' => 'http://143.233.226.49:8890',
	'personsUrl' => 'http://dashboard.linkedbusiness.gr/gr/person/',
	'companiesUrl' => 'http://dashboard.linkedbusiness.gr/gr/company/'
];